// Seed snapshot (30 Sep 2026). Overwritten daily by scripts/update_news.py
window.NEWS={updated:"2026-09-30 (seed snapshot)",
industry:[
{title:"Victoria opens Australia's first offshore wind auction",source:"Windfair",date:"2026-09-09",url:"https://w3.windfair.net/wind-energy/pr/49460-asia-offshore-wind-offshore-wind-auction-tepco-eia-pnoc-land-access-south-korea-wind-growth-china-offshore-supply-offshore-wind-logistics-taiwan-formosa-4-wind-energy-news"},
{title:"TEPCO starts EIA for new Choshi offshore wind farm; Japan plans to re-tender Mitsubishi-dropped sites",source:"Asia Wind Energy Assoc.",date:"2026-09-09",url:"https://w3.windfair.net/wind-energy/pr/49460-asia-offshore-wind-offshore-wind-auction-tepco-eia-pnoc-land-access-south-korea-wind-growth-china-offshore-supply-offshore-wind-logistics-taiwan-formosa-4-wind-energy-news"},
{title:"Glamox wins marine lighting contract for Formosa 4 (35 turbine transition pieces)",source:"Asia Wind Energy Assoc.",date:"2026-09-09",url:"https://w3.windfair.net/wind-energy/pr/49460-asia-offshore-wind-offshore-wind-auction-tepco-eia-pnoc-land-access-south-korea-wind-growth-china-offshore-supply-offshore-wind-logistics-taiwan-formosa-4-wind-energy-news"},
{title:"Ho Chi Minh City reviews feasibility study for 6 GW offshore wind project",source:"Asia Wind Energy Assoc.",date:"2026-09-09",url:"https://w3.windfair.net/wind-energy/pr/49460-asia-offshore-wind-offshore-wind-auction-tepco-eia-pnoc-land-access-south-korea-wind-growth-china-offshore-supply-offshore-wind-logistics-taiwan-formosa-4-wind-energy-news"},
{title:"South Korea selects 1,786 MW in H1 2026 auction, including floating wind",source:"Windfair",date:"2026-07-01",url:"https://w3.windfair.net/wind-energy/news/49201-onshore-wind-tender-bundesnetzagentur-south-korea-auction-us-tax-credits-floating-wind-north-sea-2050-statkraft-peru-auction-design"}],
competitors:[
{title:"CDWE (DEME/CSBC) completes Fengmiao 1 pin piles and substation ahead of schedule with Green Jade",source:"offshoreWIND.biz",date:"2026-08-05",url:"https://www.offshorewind.biz/2026/08/05/offshore-substation-export-cable-works-completed-at-taiwans-fengmiao-1"},
{title:"Jan De Nul completes Fengmiao 1 export cable connection with Willem de Vlamingh",source:"offshoreWIND.biz",date:"2026-08-05",url:"https://www.offshorewind.biz/2026/08/05/offshore-substation-export-cable-works-completed-at-taiwans-fengmiao-1"},
{title:"DEME: Sea Challenger installs first Hai Long 3 turbine, starting 2026 campaign",source:"DredgeWire",date:"2026-03-25",url:"https://dredgewire.com/deme-jv-cdwe-installs-first-turbine-at-hai-long-3-offshore-wind-farm/"},
{title:"Van Oord to start Fengmiao 1 inter-array cable works in 2027",source:"offshoreWIND.biz",date:"2025-01-13",url:"https://www.offshorewind.biz/2025/01/13/cip-signs-fengmiao-1-offshore-installation-contracts-with-van-oord-csbc-deme-jv/"}],
cadeler:[
{title:"Nexra wins additional Taiwan O&M campaign with Wind Maker (3-4 months)",source:"offshoreWIND.biz",date:"2026-03-23",url:"https://www.offshorewind.biz/2026/03/23/cadeler-bags-new-offshore-wind-om-contract-in-taiwan/"},
{title:"Nexra awarded Japan O&M contract; Wind Zaratan mobilising from Singapore",source:"offshoreWIND.biz",date:"2026-03-20",url:"https://www.offshorewind.biz/2026/03/20/cadelers-nexra-awarded-offshore-wind-om-contract-in-japan"}]};
